name: 'api_test'

services:
  mongo:
    image: mongo
    container_name: mongo_test
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    env_file:
      - .env

  redis:
    image: redis
    container_name: redis_test
    env_file:
      - .env

