name: 'api_dev'

services:
  mongo:
    image: mongo
    container_name: mongo_dev
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - ./mongo_data:/data/db
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - '${MONGO_EXPRESS_PORT}:8081'
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_SITE_PORT: 8081
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    depends_on:
      - mongo
    env_file:
      - .env

  redis:
    image: redis
    container_name: redis_dev
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./redis_data:/data
    env_file:
      - .env

  redis-insight:
    image: redis/redisinsight
    container_name: redis-ui
    restart: always
    ports:
      - '${REDIS_UI_PORT}:5540'
    depends_on:
      - redis
